config/routes.rb
BeersRails::Application.routes.draw do
  get "home/index"

  resources :beers
  root :to => "home#index"

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessible :brewery, :comment, :country, :name, :score, :style
  
  validates :name,  :presence => true
  validates :score, :presence => true,
                    :numericality => { :greater_than => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	http_basic_authenticate_with :name => "demo", :password => "demo", :except => [:index, :show]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render json: @beer, status: :created, location: @beer }
      else
        format.html { render action: "new" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/beers/_form.html.erb
<%= form_for @beer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :brewery, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brewery, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :style, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :style, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :score, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :score, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comment, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                beers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<%- model_class = Beer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/beers/index.html.erb
<%- model_class = Beer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:brewery) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:style) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.id, beer_path(beer) %></td>
        <td><%= beer.name %></td>
        <td><%= beer.brewery %></td>
        <td><%= beer.country %></td>
        <td><%= beer.style %></td>
        <td><%= beer.score %></td>
        <td><%= beer.comment %></td>
        <td><%=l beer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_beer_path(beer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      beer_path(beer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_beer_path,
            :class => 'btn btn-primary' %>

app/views/beers/new.html.erb
<%- model_class = Beer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/beers/show.html.erb
<%- model_class = Beer -%>
<div class="page-header">
  <h1><%=t '.title', :default => @beer.brewery + " - " + @beer.name %></h1>
</div>

<div class="row">
	<div class="span6">
		<dl class="dl-horizontal">
			<dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
			<dd><%= @beer.name %></dd>
			<dt><strong><%= model_class.human_attribute_name(:brewery) %>:</strong></dt>
			<dd><%= @beer.brewery %></dd>
			<dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
			<dd><%= @beer.country %></dd>
			<dt><strong><%= model_class.human_attribute_name(:style) %>:</strong></dt>
			<dd><%= @beer.style %></dd>
			<dt><strong><%= model_class.human_attribute_name(:score) %>:</strong></dt>
			<dd><%= @beer.score %></dd>
			<dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
			<dd><%= @beer.comment %></dd>			
		</dl>
	</div>
	
	<div class="span6">
		<img src="/assets/beer-placeholder.png" class="img-polaroid">
	</div>
</div>
<div class="row">
	<div class="span12">
		<div class="form-actions">
		  <%= link_to t('.back', :default => t("helpers.links.back")),
				      beers_path, :class => 'btn'  %>
		  <%= link_to t('.edit', :default => t("helpers.links.edit")),
				      edit_beer_path(@beer), :class => 'btn' %>
		  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
				      beer_path(@beer),
				      :method => 'delete',
				      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
				      :class => 'btn btn-danger' %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeersRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="padding-top: 60px;">

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<!-- Collapsation button -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
				<span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
			</a>

			<!-- Brand -->			
			<a class="brand active" style="font-family: 'Audiowide', cursive; font-size: 32px;" href="/">BEERS</a>
		
			<!-- Collapsible Items (hidden at 940px or less) -->
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="divider-vertical"></li>							
					<li class="">
						<!--<a href="/beers">Beer List</a>-->
						<%= link_to "Beer List", beers_path %>
					</li>
				</ul> <!-- ul nav -->						
			</div> <!-- nav-collapse -->
			
			<p class="navbar-text pull-right" >Welcome, <strong>test@user.com</strong>. <small>(<a href="#">logout?</a>)</small></p>
		</div>
	</div> <!-- navbar-inner -->
</div> <!-- navbar navbar-fixed-top -->

<div class="container">
	<%= yield %>
</div>

</body>
</html>